### PR TITLE
Fix link to Akka docs to be to current version

### PR DESCRIPTION
**Pull request by ktoso**
Thanks for including the link on the site!
Wanted to update it since it was linking to a very old version while the module was still experimental :-)

Thanks in advance

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ktoso Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/projectreactor.io&pullRequestId=20)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/projectreactor.io&pullRequestId=20) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ktoso Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/projectreactor.io&pullRequestId=20)!

**Comment by simonbasle** [comment]
Sorry for the delay in noticing this! Up-to-date link is better of course 😉

**Comment by ktoso** [comment]
Cool, thanks for merging 👍

**Pull request merged**
